apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest  # can be pinned
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: amperon
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-ephemeral-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-ephemeral-storage
        emptyDir:
          sizeLimit: 1Gi
