apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: argo
  name: echoing-names-everywhere
  generateName: echoing-names-everywhere-
spec:
  entrypoint: main
  templates:

    - name: main
      dag:
        tasks:
          - name: create-list-of-names
            template: create-list

          - name: argo-echo-workflow
            template: create-argo-echo-workflow
            dependencies:
              - create-list-of-names
            arguments:
              parameters:
                - name: name
                  value: "{{ item }}"
            withParam: "{{ tasks.create-list-of-names.outputs.parameters.name-list }}"

    - name: create-list
      script:
        image: busybox:latest
        command: [ sh  ]
        source: |
          echo '["foo", "bar", "baz"]' >> /tmp/names.txt
      outputs:
        parameters:
          - name: name-list
            valueFrom:
              path: /tmp/names.txt

    - name: create-argo-echo-workflow
      inputs:
        parameters:
          - name: name
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: argo-echo-
          spec:
            arguments:
              parameters:
              - name: message
                value: "hello, {{inputs.parameters.name}}"
            workflowTemplateRef:
              name: argo-echo
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)